/**
 * Mirror of PHP helpers in build-short-video-import-html-chatbot-rules.php:
 * - marketing_short_video_import_html_beat_division_visual_creative_direction_block
 * - marketing_short_video_import_html_beat_division_visual_creative_github_summary_block
 * Source of truth: PHP (queue/worker). FE mirror for preview/MCP parity.
 */

export function buildBeatDivisionVisualCreativeDirectionBlock(): string {
    return [
        '## Visual description — creative direction',
        '',
        '`visual_description` must translate the meaning of each audio segment into a clear, memorable and visually engaging scene.',
        '',
        'The highest priority is not visual complexity. The highest priority is that viewers can quickly understand or feel the intended message without relying on subtitles.',
        '',
        'The AI has full creative freedom to choose the visual concept, metaphor, composition, camera language and motion structure, provided that the result remains faithful to the audio and practical for HTML motion graphics.',
        '',
        '---',
        '',
        '### Core objectives',
        '',
        'For every beat, optimize for these goals in order:',
        '',
        '1. **Clarity** — The main idea should be understandable within the beat duration.',
        '2. **Semantic accuracy** — The visual must preserve the meaning, certainty and scope of the audio.',
        '3. **Visual interest** — The scene should create curiosity, emotion, surprise or a satisfying visual payoff.',
        '4. **Distinctiveness** — The visual should not feel like a generic technology animation or a repeated template.',
        '5. **Render feasibility** — The concept must be achievable using HTML, CSS, SVG, canvas, available media and motion graphics.',
        '',
        'When these goals conflict, prioritize clarity and semantic accuracy over spectacle.',
        '',
        '---',
        '',
        '### Creative freedom',
        '',
        'Choose the strongest visual approach for the specific audio segment.',
        '',
        'You may use any suitable visual language, including but not limited to: direct representation; visual metaphor; symbolic animation; product or interface demonstration; diagrammatic explanation; data visualization; character-driven action; environmental storytelling; visual comedy; contrast or comparison; transformation; repetition; reveal; visual illusion; a single powerful image; a continuous visual motif spanning adjacent beats; an intentionally minimal or nearly static composition.',
        '',
        'These are possibilities, not required categories. Do not force every beat into the same narrative or motion structure.',
        '',
        'A beat may: evolve through several stages; focus on one decisive action; hold on one compelling visual; delay its payoff; end unresolved; transition directly into the next beat; use a hard cut; deliberately contrast with surrounding beats.',
        '',
        'Select the structure that communicates the idea most effectively.',
        '',
        '---',
        '',
        '### Meaning before aesthetics',
        '',
        'First understand what the audio is doing. Determine internally: the single most important message; what the viewer should understand, feel or remember; whether the audio describes a fact, problem, process, benefit, emotion, comparison, instruction or call to action; which parts can be shown directly; which parts would benefit from abstraction or metaphor.',
        '',
        'Do not output this analysis. Do not begin from a preferred visual effect and then force the audio to fit it.',
        '',
        '---',
        '',
        '### Semantic fidelity',
        '',
        'Visuals must reflect the actual meaning of the source audio (`audio_script` / `phrase_anchor`).',
        '',
        'Do not turn: assistance into full automation; a possibility into a guaranteed result; a recommendation into a completed action; a target into an achieved outcome; an estimate into an exact fact; correlation into causation; a visual metaphor into a literal product capability.',
        '',
        'Do not invent: features; data; metrics; interfaces; people; locations; events; integrations; awards; results; claims not supported by the source.',
        '',
        'When the audio lacks visual detail, use a neutral abstraction rather than inventing factual specifics.',
        '',
        '---',
        '',
        '### Information clarity',
        '',
        'The scene should have one dominant communicative idea. Supporting details are allowed only when they reinforce that idea.',
        '',
        'Avoid overcrowding the frame with multiple dashboards, cards, graphs, labels or simultaneous actions unless the audio genuinely requires them.',
        '',
        'Use hierarchy so the viewer can immediately identify: what matters; what changes; what causes the change; or what result should be noticed.',
        '',
        'A simple visual with a strong idea is better than a complex visual with weak communication.',
        '',
        '---',
        '',
        '### Motion with purpose',
        '',
        'Motion should communicate meaning, direct attention or control pacing. It may express concepts such as: growth; pressure; friction; speed; connection; separation; comparison; filtering; discovery; instability; progress; repetition; cooperation; transformation.',
        '',
        'Motion is not mandatory. A static or restrained scene is valid when it communicates more effectively than continuous animation.',
        '',
        'Avoid decorative motion that competes with the main information.',
        '',
        '---',
        '',
        '### Composition and camera',
        '',
        'Choose composition and camera behavior freely according to the visual idea. The scene may use: centered or asymmetric framing; flat, isometric or dimensional space; close-up or wide framing; top-down, side-view or perspective views; continuous camera movement; a locked camera; foreground and background interaction; objects moving beyond the frame; negative space; visual continuity with nearby beats.',
        '',
        'Do not add camera movement solely to make the scene feel cinematic. Use it only when it improves attention, meaning, rhythm or impact.',
        '',
        '---',
        '',
        '### Visual rhythm across the full video',
        '',
        'Treat the entire beat map as one visual experience, not a collection of unrelated animations.',
        '',
        'Create variety in: visual scale; density; pace; depth; energy; abstraction; motion intensity; composition; use of media; emotional tone.',
        '',
        'Variety does not mean every beat must use a completely different visual language. You may intentionally reuse a motif, object or transition when it creates continuity or reinforces a central idea.',
        '',
        'Avoid accidental repetition, especially repeated use of: floating interface cards; glowing node networks; scanning grids; particle bursts; generic upward graphs; objects automatically reorganizing; centered hero objects with camera push-ins; identical before-and-after transformations.',
        '',
        'Reuse is allowed when it is narratively meaningful rather than caused by habit.',
        '',
        '---',
        '',
        '### Text restrictions (planning level)',
        '',
        'The HTML beat is visual-only. Do not plan for: subtitles; karaoke; voiceover sentences; `phrase_anchor` on screen; Whisper transcripts; word-by-word highlights; paragraph-length UI copy; explanatory captions.',
        '',
        'Minimal diegetic text may be planned only when essential to the visual concept (short command, filename, a number from the source, brief UI label, recognizable status). The visual must still communicate without depending primarily on this text.',
        '',
        '(Authoritative karaoke bans are also listed in the Vietnamese no-karaoke section above.)',
        '',
        '---',
        '',
        '### Media usage',
        '',
        'Use zero or one catalog media item per beat. Choose media only when it materially improves recognition, credibility or communication.',
        '',
        'When using an item: reference its exact ID inside backticks; explain how it is framed or integrated into the scene; do not invent details outside the media; do not reuse the same item in another beat.',
        '',
        'Do not force media into a beat when an original motion-graphic concept would communicate better. Exact catalog rules and allowed IDs are in the visual library section below.',
        '',
        '---',
        '',
        '### Background',
        '',
        'Generate a concise English `background` description for each beat. It should support the hero visual through depth, texture, atmosphere or contrast without overriding the global visual system.',
        '',
        'Do not redefine: the global palette; typography; font family; theme; aspect ratio; rendering framework; brand identity.',
        '',
        'Avoid repeating the same background wording across the video.',
        '',
        '---',
        '',
        '### Visual description output',
        '',
        'Each `visual_description` must:',
        '',
        '- be written in English;',
        '- **prefer 20–120 words**; hard allow **5–150 words** (≤1200 characters) — use 5–19 only for very short beats;',
        '- describe a concrete, renderable visual idea;',
        '- identify the main subject or focal event;',
        '- explain important movement or visual change when applicable;',
        '- make the intended communication clear;',
        '- avoid explaining the reasoning behind the creative choice;',
        '- avoid raw double quotes;',
        '- contain no HTML or implementation code.',
        '',
        'There is no required sentence count or mandatory scene structure. Use as much or as little detail as necessary to make the concept unambiguous.',
        '',
        '---',
        '',
        '### Internal evaluation',
        '',
        'Before returning the beat map, evaluate each visual internally:',
        '',
        '- Would a viewer understand the intended idea without subtitles?',
        '- Is the visual faithful to the audio?',
        '- Is the scene interesting enough to hold attention?',
        '- Is the concept more specific than a generic animation template?',
        '- Does every major element contribute to communication?',
        '- Is the scene practical to implement?',
        '- Does it avoid unsupported claims?',
        '- Does it contribute positively to the rhythm of the full video?',
        '',
        'If a visual is accurate but dull, improve the concept. If exciting but unclear, simplify it. If clear but too similar to nearby beats, find a more distinctive treatment.',
        '',
        'Do not output this evaluation.',
        '',
        '---',
        '',
        '### Bridge to HTML fill',
        '',
        'The beat map is a **visual plan** grounded in `audio_script` and `phrase_anchor`. Later HTML generation will enforce a creative-truth contract (no invented facts/metrics). Plan visuals that stay faithful to the source so fill does not have to invent or contradict.',
        '',
    ].join('\n');
}

export function buildBeatDivisionVisualCreativeGithubSummaryBlock(): string {
    return [
        '## Visual description — creative summary (GitHub top)',
        '',
        'Within the fixed intro / one-repo-per-beat / outro structure, each `visual_description` still must prioritize:',
        '',
        '1. **Clarity** — viewer understands the beat idea without subtitles.',
        '2. **Semantic accuracy** — faithful to the audio for that segment (intro list, that repo, or outro/CTA).',
        '3. **Visual interest** and **distinctiveness** — avoid generic tech templates.',
        '4. **Render feasibility** — HTML/CSS/SVG/canvas + optional catalog media.',
        '',
        'Meaning before aesthetics: derive the concept from the audio, not from a preferred effect.',
        '',
        'Semantic fidelity: do not invent stars, claims, features, or results not in the script; do not turn metaphor into a false product claim.',
        '',
        'Avoid accidental repetition across beats: floating cards, glowing node networks, scanning grids, particle bursts, generic upward graphs, identical camera push-ins.',
        '',
        'Each `visual_description`: English; **prefer 20–120 words**; hard allow **5–150** (≤1200 chars); no raw double quotes; no HTML. Use 5–19 only for very short intro/outro if needed.',
        '',
        'Do not plan karaoke/subtitles; `phrase_anchor` is planning metadata only.',
        '',
    ].join('\n');
}
