/**
 * Mirror of PHP helpers in build-short-video-import-html-chatbot-rules.php:
 * - marketing_short_video_import_html_beat_division_visual_creative_direction_block
 * - marketing_short_video_import_html_beat_division_visual_creative_github_summary_block
 * Source of truth: PHP (queue/worker). FE mirror for preview/MCP parity.
 */

export function buildBeatDivisionVisualCreativeDirectionBlock(): string {
    return [
        '## Visual description — creative direction',
        '',
        '`visual_description` must translate the meaning of each audio segment into a clear, memorable and visually engaging scene.',
        '',
        'The highest priority is not visual complexity. The highest priority is that viewers can quickly understand the message through visible cause and effect, without relying on subtitles.',
        '',
        '---',
        '',
        '### Core objectives',
        '',
        'For every beat, optimize for these goals in order:',
        '',
        '1. **Clarity** — The main idea should be understandable within the beat duration.',
        '2. **Clear object system** — One coherent cast of subjects/props; the viewer can name what is on screen.',
        '3. **Semantic accuracy** — The visual must preserve the meaning, certainty and scope of the audio.',
        '4. **Visual causality** — The consequence should emerge from the action, not from a warning symbol or headline.',
        '5. **Low text dependency** — Communicate through objects and motion; on-screen text is optional and never the primary carrier.',
        '6. **Render feasibility** — The concept must be achievable using HTML, CSS, SVG, canvas, available media and motion graphics.',
        '',
        'When these goals conflict, prioritize clarity, object system, semantic accuracy, and causality.',
        '',
        '---',
        '',
        '### Meaning before aesthetics',
        '',
        'First understand what the audio is doing. Determine internally: the single most important message; what the viewer should understand, feel or remember; whether the audio describes a fact, problem, process, benefit, emotion, comparison, instruction or call to action; which parts can be shown directly; which parts would benefit from abstraction or metaphor.',
        '',
        'Do not output this analysis. Do not begin from a preferred visual effect and then force the audio to fit it.',
        '',
        '---',
        '',
        '### Semantic fidelity',
        '',
        'Visuals must reflect the actual meaning of the source audio (`audio_script` / `phrase_anchor`).',
        '',
        'Do not turn: assistance into full automation; a possibility into a guaranteed result; a recommendation into a completed action; a target into an achieved outcome; an estimate into an exact fact; correlation into causation; a visual metaphor into a literal product capability.',
        '',
        'Do not invent: features; data; metrics; interfaces; people; locations; events; integrations; awards; results; claims not supported by the source.',
        '',
        'When the audio lacks visual detail, use a neutral abstraction rather than inventing factual specifics.',
        '',
        '---',
        '',
        '### Information clarity',
        '',
        'The scene should have one dominant communicative idea. Supporting details are allowed only when they reinforce that idea.',
        '',
        'Avoid overcrowding the frame with multiple dashboards, cards, graphs, labels or simultaneous actions unless the audio genuinely requires them.',
        '',
        'Use hierarchy so the viewer can immediately identify: what matters; what changes; what causes the change; or what result should be noticed.',
        '',
        'A simple visual with a strong idea is better than a complex visual with weak communication.',
        '',
        '---',
        '',
        '### Semantic visual concept — style-neutral',
        '',
        '`visual_description` is a semantic concept brief for a later HTML composer.',
        'Define what the scene communicates, not how the final interface should be styled.',
        '',
        'Describe:',
        '- the concrete hero subject;',
        '- recognizable supporting objects;',
        '- the relationship or conflict between them;',
        '- the main action or transformation;',
        '- the visually obvious consequence;',
        '- the final state the viewer should recognize.',
        '',
        'Do not prescribe:',
        '- visual style, palette, typography, or grid;',
        '- UI treatment or exact layout;',
        '- camera lens behavior;',
        '- CSS effects, HTML structure, or implementation details.',
        '',
        'The HTML composer will determine execution from `VISUAL_STYLE`, `RESOLVED_ART_DIRECTION`, and `BACKGROUND`.',
        '',
        '---',
        '',
        '### Concrete semantic anchors',
        '',
        'Prefer recognizable objects, environments, and actions over generic geometry.',
        '',
        'Good anchors include: comedy mask, football, film clapper, microphone, crowded shelf, specialist storefront, sorting machine, branching road, narrowing category path, creator workspace, audience cluster, jammed distribution system.',
        '',
        'Weak anchors include: rectangle representing a channel, abstract geometric shapes, energy field, glowing beam, generic cards, floating particles, innovation pulse, futuristic network.',
        '',
        'Geometric shapes are allowed only when their meaning is established through clear relationships, transformations, or recognizable context.',
        '',
        '---',
        '',
        '### Visual causality',
        '',
        'Each concept should contain visible cause-and-effect.',
        '',
        'The viewer should infer: what initiates the action, what changes, why it changes, and what consequence remains at the end.',
        '',
        'Do not use a final symbol, stamp, warning icon, or headline as a substitute for showing consequence.',
        'Whenever possible, let the result emerge naturally from the action.',
        '',
        '---',
        '',
        '### No explanation-dependent metaphor',
        '',
        'Do not use metaphors that only make sense because text explains what each shape represents.',
        '',
        'Avoid concepts that require statements such as: the rectangle represents the channel; the beam represents growth; the triangle represents focus; floating shapes represent trends.',
        '',
        'Use recognizable objects, or build relationships that make meaning self-evident.',
        'The concept should still be understandable when explanatory wording is removed.',
        '',
        '---',
        '',
        '### Composer freedom',
        '',
        'Preserve semantic intent while leaving execution freedom to the HTML composer.',
        '',
        'Do not require every listed object to appear literally.',
        '',
        'The composer may simplify, merge, or reinterpret supporting objects, but these must remain clear:',
        '- hero subject;',
        '- primary action;',
        '- cause-and-effect relationship;',
        '- emotional direction;',
        '- final recognizable consequence.',
        '',
        '---',
        '',
        '### Visual rhythm across the full video',
        '',
        'Treat the entire beat map as one visual experience, not a collection of unrelated animations.',
        '',
        'Create variety in: visual scale; density; pace; depth; energy; abstraction; motion intensity; composition; use of media; emotional tone.',
        '',
        'Variety does not mean every beat must use a completely different visual language. You may intentionally reuse a motif, object or transition when it creates continuity or reinforces a central idea.',
        '',
        'Avoid accidental repetition, especially repeated use of: floating interface cards; glowing node networks; scanning grids; particle bursts; generic upward graphs; objects automatically reorganizing; centered hero objects with camera push-ins; identical before-and-after transformations.',
        '',
        'Reuse is allowed when it is narratively meaningful rather than caused by habit.',
        '',
        '### Visual rhythm QA rubric (enforced after division)',
        '',
        'The pipeline runs a strict Visual rhythm QA on the full beat map before HTML fill. Pass = no critical issues.',
        '',
        'Critical issues include: `communicative_overload` (≥2 unrelated communicative units in one beat); `adjacent_layout_repeat` (adjacent beats share card/scaffold/layout — including github_top repo beats); `dashboard_fatigue`; `visual_variety_low`; `cta_visual_collision`; `voiceover_visual_mismatch`; `visual_underdeveloped`; `rhythm_monotonous`.',
        '',
        'Communicative unit examples: repo hot + stars + forks in one 14s beat = OK (same unit). Repo stats + compatibility + feature intro in one beat = critical overload.',
        '',
        'Adjacent repo beats must differ in composition/motion even when the topic is similar.',
        '',
        '---',
        '',
        '### Text restrictions (planning level)',
        '',
        'The HTML beat is visual-only. Do not plan for: subtitles; karaoke; voiceover sentences; `phrase_anchor` on screen; Whisper transcripts; word-by-word highlights; paragraph-length UI copy; explanatory captions.',
        '',
        'Minimal diegetic text may be planned only when essential to the visual concept (short command, filename, a number from the source, brief UI label, recognizable status). The visual must still communicate without depending primarily on this text.',
        '',
        '(Authoritative karaoke bans are also listed in the Vietnamese no-karaoke section above.)',
        '',
        '---',
        '',
        '### Media usage',
        '',
        'Use zero or one catalog media item per beat. Choose media only when it materially improves recognition, credibility or communication.',
        '',
        'When using an item: reference its exact ID inside backticks; explain how it is framed or integrated into the scene; do not invent details outside the media; do not reuse the same item in another beat.',
        '',
        'Do not force media into a beat when an original motion-graphic concept would communicate better. Exact catalog rules and allowed IDs are in the visual library section below.',
        '',
        '---',
        '',
        '### Background',
        '',
        'Generate a concise English `background` description for each beat. It should support the hero visual through depth, texture, atmosphere or contrast without overriding the global visual system.',
        '',
        'Do not redefine: the global palette; typography; font family; theme; aspect ratio; rendering framework; brand identity.',
        '',
        'Avoid repeating the same background wording across the video.',
        '',
        '---',
        '',
        '### Visual description output',
        '',
        'Each `visual_description` must:',
        '',
        '- be written in English;',
        '- use approximately **40–100 words**;',
        '- describe one dominant semantic visual concept;',
        '- identify one concrete hero subject;',
        '- use recognizable objects or environments when possible;',
        '- show one clear action, conflict, or transformation;',
        '- show a visually obvious consequence;',
        '- define a recognizable final state;',
        '- remain style-neutral and implementation-neutral;',
        '- remain practical for HTML motion graphics;',
        '- avoid explaining the reasoning behind the creative choice;',
        '- avoid raw double quotes;',
        '- contain no HTML, CSS, layout measurements, or implementation code;',
        '- contain no palette, typography, or visual-style instructions.',
        '',
        '---',
        '',
        '### Internal evaluation',
        '',
        'Before returning the beat map, evaluate each visual internally:',
        '',
        '- Can it be summarized as: a concrete subject does something that causes a clear result?',
        '- Would the action still make sense without a headline?',
        '- Are the main objects recognizable without explanatory labels?',
        '- Does the consequence emerge from the action rather than from a red X, warning icon, or explanatory text?',
        '- Is the description semantic and style-neutral?',
        '- Does it leave enough freedom for the HTML composer to apply any suitable `VISUAL_STYLE`?',
        '- Can it be implemented cleanly without excessive DOM complexity?',
        '',
        'If the concept relies on generic shapes, labels, or explanation, replace it with a clearer object relationship or physical process.',
        '',
        '---',
        '',
        '### Bridge to HTML fill',
        '',
        'Beat splitter defines WHAT happens and WHY it matters.',
        'HTML composer defines HOW it looks and HOW it moves.',
        '',
        'The beat map is a semantic visual plan grounded in `audio_script` and `phrase_anchor`. Later HTML generation enforces creative truth and art direction.',
        '',
    ].join('\n');
}

export function buildBeatDivisionVisualCreativeGithubSummaryBlock(): string {
    return [
        '## Visual description — creative summary (GitHub top)',
        '',
        'Within the fixed intro / one-repo-per-beat / outro structure, each `visual_description` still must prioritize:',
        '',
        '1. **Clarity** — viewer understands the beat idea without subtitles.',
        '2. **Concrete semantic anchors + clear object system** — recognizable subjects/props, not explanation-dependent geometry.',
        '3. **Visible causality** — action should produce a clear consequence naturally, not via warning symbols.',
        '4. **Semantic accuracy** — faithful to the audio for that segment (intro list, that repo, or outro/CTA).',
        '5. **Low text dependency** — communicate through objects and motion, not subtitle-like copy.',
        '6. **Render feasibility** — practical for HTML/CSS/SVG/canvas + optional catalog media.',
        '',
        'Beat splitter defines WHAT/WHY; HTML composer defines HOW (style/layout/typography/motion execution).',
        '',
        'Semantic fidelity: do not invent stars, claims, features, or results not in the script; do not turn metaphor into a false product claim.',
        '',
        'Prefer recognizable objects and relationships over generic rectangles, beams, particles, or symbolic X-stamps.',
        '',
        'Each `visual_description`: English, approximately 40–100 words, semantic and style-neutral, no raw double quotes, no HTML/CSS/layout instructions.',
        '',
        'Do not plan karaoke/subtitles; `phrase_anchor` is planning metadata only.',
        '',
    ].join('\n');
}
