export const AGENT_VIDEO_FILMSTRIP_INTERVAL_SEC = 3.5;
export const AGENT_VIDEO_FILMSTRIP_CAPTURE_VERSION = 2;

export const AGENT_VIDEO_TIMELINE_SCALE_WIDTH = 56;
export const AGENT_VIDEO_TIMELINE_SCALE = 1;
